# =========================================
# Stage 1: Develop the React.js Application
# =========================================
ARG NODE_VERSION=20-alpine

# Use a lightweight Node.js image for development
FROM node:${NODE_VERSION} AS dev

# Set the working directory inside the container
WORKDIR /app_front-end

# Copy package-related files first to leverage Docker's caching mechanism
COPY package.json package-lock.json ./ 

# Install project dependencies
RUN --mount=type=cache,target=/root/.npm npm ci 

# Copy the rest of the application source code into the container
COPY . .

# Expose the port used by the Vite development server
EXPOSE 5173

# Use a default command, can be overridden in Docker compose.yml file
CMD ["npm","run","dev","--","--host","0.0.0.0"]


ENV HOST=0.0.0.0